#	$NetBSD: Makefile,v 1.11 2019/09/29 23:44:59 mrg Exp $

SRCS=		allow.c board.c check.c fancy.c init.c odds.c \
		one.c save.c subs.c table.c
OBJS=		allow.o board.o check.o fancy.o init.o odds.o \
		one.o save.o subs.o table.o

all: objs

objs: $(OBJS)

clean:
	rm -f $(OBJS)

.PHONY: all clean
